[bot]
adapters = ["alicebot.adapter.mirai","alicebot.adapter.apscheduler"]

[adapter.mirai]
adapter_type = "ws"

qq = 3267653962

[adapter.apscheduler]
scheduler_config = { "apscheduler.timezone" = "Asia/Shanghai" }